### ISSUE TITLE
TypeError: glfw3_render() missing 2 required positional arguments: 'vertex_buffer_size' and 'element_buffer'

### ISSUE THREAD

**Issue by sphaero** [billsix/pyNuklear#3]
When running the opengl2 demo: 
```
PYTHONPATH="." python3 demo/glfw_opengl2/pyNuklearGLFWOpenGL2.py 
Traceback (most recent call last):
  File "demo/glfw_opengl2/pyNuklearGLFWOpenGL2.py", line 262, in <module>
    nkGLFW3.glfw3_render(nk.AntiAliasing.ON.value)
TypeError: glfw3_render() missing 2 required positional arguments: 'vertex_buffer_size' and 'element_buffer'
```

The opengl3 demo works

**Comment by sphaero** [comment]
although it crashes when clicking somewhere :S
```
PYTHONPATH="." python3 demo/glfw_opengl3/pyNuklearGLFWOpenGL3.py 
button pressed
button pressed
button pressed
button pressed
button pressed
Traceback (most recent call last):
  File "demo/glfw_opengl3/pyNuklearGLFWOpenGL3.py", line 280, in <module>
    overview(nuklear)
  File "/home/arnaud/src/pyNuklear/demo/overview.py", line 938, in overview
    if hoveredIndex != -1:
UnboundLocalError: local variable 'hoveredIndex' referenced before assignment
```

**Comment by billsix** [comment]
Both should be fixed by commit https://github.com/billsix/pyNuklear/commit/771b1f67caec651be1a6c14707816e1bec50b02e

Please let me know if you have more issues.
