### ISSUE TITLE
Installing PyNuklear throws errors

### ISSUE THREAD

**Issue by D3SERTed** [billsix/pyNuklear#9]
running the setup.py leads to an error see below
`setup.py install
running install
running bdist_egg
running egg_info
writing pyNuklear.egg-info\PKG-INFO
writing dependency_links to pyNuklear.egg-info\dependency_links.txt
writing requirements to pyNuklear.egg-info\requires.txt
writing top-level names to pyNuklear.egg-info\top_level.txt
Traceback (most recent call last):
  File "C:\Users\root\Downloads\pyNuklear-master\pyNuklear-master\setup.py", line 40, in <module>
    ext_modules = [module1]
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
    self.find_sources()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
    mm.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
    self.add_defaults()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\command\sdist.py", line 226, in add_defaults
    self._add_defaults_python()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\sdist.py", line 127, in _add_defaults_python
    build_py = self.get_finalized_command('build_py')
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_py.py", line 34, in finalize_options
    orig.build_py.finalize_options(self)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_py.py", line 55, in finalize_options
    self.package_dir[name] = convert_path(path)
  File "C:\Users\root\AppData\Local\Programs\Python\Python37\lib\distutils\util.py", line 112, in convert_path
    raise ValueError("path '%s' cannot end with '/'" % pathname)
ValueError: path 'src/pynuklear/demo/' cannot end with '/'`

**Comment by billsix** [comment]
I've never gotten it to work on Windows.  Any help would be appreciated.
